spring:
    datasource:
        url: jdbc:mysql://111.231.135.83:33307/rental-system?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: kimen
        password: mys@l@kimen
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082
  servlet:
    context-path: /rental-system

qiniuyun:
    ak: T5XQB_CwNFrIdhVvTClo66SdRdUhGPIt6K2iFE4Y
    sk: kJKqehmTegWIXZrR9AkZ2agrV38zZJ1wQypEYwue
    bucket: hsd-server
    outline: http://img.kimen.xyz/